import {
  renderScriptureSkeletonPlan,
  type ScriptureSkeletonPlan,
} from "../lib/scriptureSkeletons";

const plan: ScriptureSkeletonPlan = {
  textType: "冲突记事",
  units: [
    { kind: "narration", frame: "arrival", actor: "刘华强", place: "摆设筵席的屋里" },
    { kind: "narration", frame: "reaction", actor: "伺候筵席的人", target: "刘华强等人", action: "引导他们往里面走" },
    { kind: "speech", intent: "waited_arrival", speaker: "宋老虎", addressee: "刘华强", elements: {} },
    { kind: "speech", intent: "introduction", speaker: "刘华强", addressee: "宋老虎", elements: { count: "两", names: "跃平、大海", relation: "我的兄弟" } },
    { kind: "speech", intent: "invite_seat", speaker: "宋老虎", addressee: "刘华强", elements: {} },
    { kind: "narration", frame: "action", actor: "大海", action: "把带来之物摆在席前" },
    { kind: "speech", intent: "courtesy_gift", speaker: "宋老虎", addressee: "刘华强", elements: { gift: "礼物" } },
    { kind: "speech", intent: "courtesy_refusal", speaker: "刘华强", addressee: "宋老虎", elements: { relation: "自家兄弟" } },
    { kind: "speech", intent: "introduction", speaker: "宋老虎", addressee: "刘华强", elements: { count: "一", names: "振涛", relation: "我的兄弟" } },
    { kind: "speech", intent: "self_identification", speaker: "刘华强", addressee: "振涛", elements: { name: "刘华强" } },
    { kind: "speech", intent: "reputation", speaker: "宋老虎", addressee: "刘华强", elements: { qualities: "重义气、讲情分" } },
    { kind: "speech", intent: "offer_help", speaker: "宋老虎", addressee: "刘华强", elements: { matter: "所求的事" } },
    { kind: "speech", intent: "reassurance", speaker: "刘华强", addressee: "宋老虎", elements: { basis: "大哥这一句话" } },
    { kind: "speech", intent: "infer_motive", speaker: "刘华强", addressee: "宋老虎", elements: { surface: "坐席吃喝", matter: "别的事" } },
    { kind: "speech", intent: "request_directness", speaker: "刘华强", addressee: "宋老虎", elements: { matter: "今日请我来的缘故" } },
    { kind: "speech", intent: "approval", speaker: "宋老虎", addressee: "刘华强", elements: { quality: "痛快、喜欢这脾气" } },
    { kind: "speech", intent: "mediation_request", speaker: "宋老虎", addressee: "刘华强", elements: { beneficiary: "赵祥生", action: "不要再寻找赵祥生", result: "看我的情面" } },
    { kind: "speech", intent: "mutual_claim", speaker: "刘华强", addressee: "宋老虎", elements: { theirs: "宋大哥的兄弟", mine: "华强的朋友" } },
    { kind: "speech", intent: "self_defense", speaker: "刘华强", addressee: "宋老虎", elements: { matter: "向赵祥生借钱", rejected: "不还", asserted: "借用一时" } },
    { kind: "speech", intent: "insult_challenge", speaker: "振涛", addressee: "刘华强", delivery: "cried", elements: { knownA: "我哥在道上混时", knownB: "你穿年幼无知", challenge: "在我哥哥面前摆架子" } },
    { kind: "speech", intent: "rebuke", speaker: "宋老虎", addressee: "振涛", elements: { prohibition: "不可不要再说无礼的话" } },
    { kind: "speech", intent: "paired_dominance", speaker: "刘华强", addressee: "振涛", elements: { categoryA: "龙", resultA: "盘着", categoryB: "虎", resultB: "卧着" } },
    { kind: "speech", intent: "relay_request", speaker: "刘华强", addressee: "宋老虎", elements: { target: "赵祥生", matter: "叫他自己来跟我说" } },
    { kind: "narration", frame: "action", actor: "刘华强", action: "站起身来，预备带着韩跃平和大海离开" },
    { kind: "speech", intent: "warning_pride", speaker: "宋老虎", addressee: "刘华强", elements: { warning: "太气盛" } },
    { kind: "speech", intent: "youth_defiance", speaker: "刘华强", addressee: "宋老虎", elements: { quality: "气盛" } },
    { kind: "speech", intent: "exit_threat", speaker: "振涛", addressee: "刘华强", delivery: "cried", elements: { condition: "这样走出房子", consequence: "追讨这事" } },
    { kind: "speech", intent: "method_challenge", speaker: "刘华强", addressee: "振涛", delivery: "asked", elements: { action: "走出这个屋子" } },
    { kind: "speech", intent: "coercion", speaker: "振涛", addressee: "刘华强", elements: { positiveCondition: "愿意答应", negativeCondition: "不愿意答应", result: "答应" } },
    { kind: "speech", intent: "boast", speaker: "刘华强", addressee: "振涛", elements: { action: "这样跟我说话" } },
    { kind: "speech", intent: "death_threat", speaker: "振涛", addressee: "刘华强", delivery: "cried", elements: { target: "刘华强" } },
    { kind: "narration", frame: "action", actor: "振涛", action: "向刘华强扑过去" },
    { kind: "narration", frame: "action", actor: "韩跃平", action: "迎上前去，用刀刺伤振涛" },
    { kind: "narration", frame: "action", actor: "大海", action: "制住宋老虎", result: "使他不能上前" },
    { kind: "narration", frame: "outcome", actor: "刘华强", action: "带着韩跃平和大海离去" },
    { kind: "narration", frame: "outcome", actor: "振涛", action: "捂住伤口" },
    { kind: "narration", frame: "outcome", actor: "宋老虎", action: "眼看着他们离开" },
  ],
};

console.log(renderScriptureSkeletonPlan(plan));
